### ISSUE TITLE
'Pyxis.Commands' has no attribute 'loadconf'

### ISSUE THREAD

**Issue by matthieutrs** [ska-sa/pyxis#98]
Hello,

We managed to build Pyxis from source just fine. Yet, when launching some pyxis commant, we keep getting that error message:

```
Traceback (most recent call last):
  File ".../pyxis/1.7.0/bin/pyxis", line 45, in <module>
    from Pyxis.Commands import _info as info
  File ".../pyxis/1.7.0/lib/python3.6/site-packages/Pyxis/__init__.py", line 68, in <module>
    Pyxis.Internals.initconf();
  File ".../pyxis/1.7.0/lib/python3.6/site-packages/Pyxis/Internals.py", line 776, in initconf
    Pyxis.Commands.loadconf(filename,inspect.currentframe().f_back,chdir=True);
AttributeError: module 'Pyxis.Commands' has no attribute 'loadconf'
```

Would have any clue on how to solve this?

**Comment by o-smirnov** [comment]
Strange how this bug slipped through all this time! Could you try changing the offending line to plain:
```
loadconf(filename,inspect.currentframe().f_back,chdir=True)
```
and see if that solves the problem?

**Comment by matthieutrs** [comment]
That solved the issue, thanks a lot!!
